name: Deploy AI Doctor to RDP

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Backend
        run: |
          cd AIDoctor.Server
          dotnet publish -c Release -o ../publish

      - name: Build Frontend
        run: |
          cd AIDoctor.Client
          npm install
          npm audit fix
          npm run build
          mkdir -p ../publish/wwwroot
          cp -r dist/* ../publish/wwwroot

      - name: Deploy to RDP
        uses: appleboy/scp-action@master
        with:
          host: "[2600:4040:7978:200:20e2:6b78:527b:f0f2]"
          username: "Aaban"
          password: ${{ secrets.RDP_PASSWORD }}
          source: "publish/*"
          target: "C:\\AI-Doctor\\publish"
          strip_components: 1

      - name: Restart App
        uses: appleboy/ssh-action@master
        with:
          host: "[2600:4040:7978:200:20e2:6b78:527b:f0f2]"
          username: "Aaban"
          password: ${{ secrets.RDP_PASSWORD }}
          script: |
            taskkill /IM dotnet.exe /F || exit 0
            start /B dotnet C:\\AI-Doctor\\publish\\AIDoctor.Server.dll --urls http://[::]:5001
