name: Deploy Frontend to Windows Server

on:
  push:
    branches:
      - main

jobs:
  frontend_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: AIDoctor.client/package-lock.json

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build React App
        run: |
          npm run build || { echo "React build failed!"; exit 1; }
          echo "Checking if dist directory exists..."
          ls -la dist || { echo "Dist directory missing!"; exit 1; }


      - name: Build Frontend
        run: |
          cd AIDoctor.client
          npm run build

      - name: Deploy Frontend via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "AIDoctor.client/dist/*"
          target: "${{ secrets.FRONTEND_DIR }}"

      - name: Restart IIS for Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            IISReset

      - name: Frontend Deployment Complete
        run: echo "Frontend successfully deployed!"
