name: Deploy Frontend and Backend to Home Server

on:
  push:
    branches:
      - main

jobs:
  # 🚀 React Frontend Deployment (Vite)
  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AIDoctor.client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: AIDoctor.client/package-lock.json

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build React App (Vite)
        run: |
          npm run build || { echo "React build failed!"; exit 1; }
          echo "Checking if dist directory exists..."
          ls -la dist || { echo "Build directory missing!"; exit 1; }

      - name: Debug - Check Build Output
        run: |
          echo "Contents of dist folder:"
          ls -la AIDoctor.client/dist

      - name: Deploy Frontend on Home Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            powershell -Command "if (Test-Path 'C:/WebApps/AIDoctor/client') { Remove-Item -Path 'C:/WebApps/AIDoctor/client/*' -Recurse -Force }"
            powershell -Command "Copy-Item -Path '~/AIDoctor.client/dist/*' -Destination 'C:/WebApps/AIDoctor/client/' -Recurse -Force"

  # 🖥️ Backend API Deployment (.NET Core)
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AIDoctor.Server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish API
        run: dotnet publish -c Release -o publish --no-restore

      - name: Debug - Check Publish Output
        run: |
          echo "Publish directory contents:"
          ls -la publish || { echo "Publish directory missing!"; exit 1; }

      - name: Deploy Backend on Home Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            powershell -Command "if (Test-Path 'C:/WebApps/AIDoctor/server') { Remove-Item -Path 'C:/WebApps/AIDoctor/server/*' -Recurse -Force }"
            powershell -Command "Copy-Item -Path '~/AIDoctor.Server/publish/*' -Destination 'C:/WebApps/AIDoctor/server/' -Recurse -Force"

            # Restart Backend Service
            powershell -Command "
              if (-not (Get-Service -Name 'AIDoctorServer' -ErrorAction SilentlyContinue)) {
                nssm install AIDoctorServer 'C:\Program Files\dotnet\dotnet.exe' 'C:\WebApps\AIDoctor\server\AIDoctor.Server.dll'
                nssm set AIDoctorServer AppDirectory 'C:\WebApps\AIDoctor\server'
              }
              nssm restart AIDoctorServer
            "
