name: Deploy Frontend and Backend to Home Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # React Frontend Deployment (Vite)
  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AIDoctor.client  # Set working directory for all steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: AIDoctor.client/package-lock.json

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build Vite React App
        run: |
          npm run build || { echo "React build failed!"; exit 1; }
          echo "Checking if dist directory exists..."
          ls -la dist || { echo "Dist directory missing!"; exit 1; }

      - name: Deploy Frontend to Home Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "AIDoctor.client/dist/*"
          target: "/c/WebApps/AIDoctor/client"

  # Backend API Deployment (.NET)
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AIDoctor.Server  # Set working directory for all steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Use .NET 9 as specified

      - name: Restore dependencies
        run: dotnet restore

      - name: Build API
        run: dotnet build --configuration Release

      - name: Publish API
        run: dotnet publish -c Release -o publish --no-restore

      - name: Debug - Check Publish Output
        run: |
          echo "Publish directory contents:"
          ls -la publish || { echo "Publish directory missing!"; exit 1; }

      - name: Deploy Backend to Home Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "AIDoctor.Server/publish/*"
          target: "/c/WebApps/AIDoctor/server"

      - name: Restart Backend Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Stop the backend service (if running)
            nssm stop AIDoctorServer || true
            # Install as a service (first time only)
            if ! nssm status AIDoctorServer; then
              nssm install AIDoctorServer "C:\Program Files\dotnet\dotnet.exe" "C:\WebApps\AIDoctor\server\AIDoctor.Server.dll"
              nssm set AIDoctorServer AppDirectory "C:\WebApps\AIDoctor\server"
            fi
            # Start the backend service
            nssm start AIDoctorServer
